### ISSUE TITLE
多选问题

### ISSUE THREAD

**Issue by yilongchun** [xmy0010/DemoForCSDN#1]
`#pragma mark <UITableViewDelegate>  
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {  
      
    NSArray *subviews = [[tableView cellForRowAtIndexPath:indexPath] subviews];  
      
    for (id obj in subviews) {  
        if ([obj isKindOfClass:[UIControl class]]) {  
  
            for (id subview in [obj subviews]) {  
                if ([subview isKindOfClass:[UIImageView class]]) {  
                      
                    [subview setValue:blueBackground forKey:@"tintColor"];  
                    break;  
                }  
                  
            }  
        }  
    }  
}  
`
这个方法是设置 点击后左边勾的颜色 有没有办法设置点击的时候左边勾的颜色 他默认还是蓝色的

**Comment by xmy0010** [comment]
你好，是可以实现的。 一般这样你可以自定cell，如果还是想用系统的话我给你提供一下我的思路。
1.首先我理解到你的意思是 cell默认没有选中情况下是蓝色的  选中之后是红色 不知道对不对
2.你上面那段代码 目前其实有更方便简单的系统API可以实现改变选中颜色，git上面已经更新了
3.实现    设置所有的cell都是选中状态  通过改变cel的tintcolor来设置颜色
4.点击“选中”和“取消选中”实际上是改变数据 和颜色 对于系统来说 所有的cell都是选中的
5.需要代码的话可以留下邮箱我发一个Demo给你

有其他意见和建议欢迎一起探讨。18144200589@163.com

**Comment by yilongchun** [comment]
我发现 设置 cell.tintColor 就可以改变颜色

**Comment by xmy0010** [comment]
是的 我代码和博客在之前已经更新过不需要那么麻烦  简单设置tintCorlor就可以实现了
